In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re,string

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import stopwords
stopwords.words('english')
import string
string.punctuation
from nltk.stem.porter import PorterStemmer

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import Callback, ReduceLROnPlateau, EarlyStopping

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [ ]:
import spacy

nlp = spacy.load("en_core_web_sm")

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


In [ ]:
data=pd.read_csv("/content/train.csv")

In [ ]:
data

TITLE  \
0            Reconstructing Subject-Specific Effect Maps   
1                     Rotation Invariance Neural Network   
2      Spherical polyharmonics and Poisson kernels fo...   
3      A finite element approximation for the stochas...   
4      Comparative study of Discrete Wavelet Transfor...   
...                                                  ...   
20963  Contemporary machine learning: a guide for pra...   
20964  Uniform diamond coatings on WC-Co hard alloy c...   
20965  Analysing Soccer Games with Clustering and Con...   
20966  On the Efficient Simulation of the Left-Tail o...   
20967   Why optional stopping is a problem for Bayesians   

                                                ABSTRACT  Computer Science  \
0        Predictive models allow subject-specific inf...                 1   
1        Rotation invariance and translation invarian...                 1   
2        We introduce and develop the notion of spher...                 0   
3        The stochastic Landau--Lifshitz--Gilbert (LL...                 0   
4        Fourier-transform infra-red (FTIR) spectra o...                 1   
...                                                  ...               ...   
20963    Machine learning is finding increasingly bro...                 1   
20964    Polycrystalline diamond coatings have been g...                 0   
20965    We present a new approach for identifying si...                 1   
20966    The sum of Log-normal variates is encountere...                 0   
20967    Recently, optional stopping has been a subje...                 0   

       Physics  Mathematics  Statistics  Quantitative Biology  \
0            0            0           0                     0   
1            0            0           0                     0   
2            0            1           0                     0   
3            0            1           0                     0   
4            0            0           1                     0   
...        ...          ...         ...                   ...   
20963        1            0           0                     0   
20964        1            0           0                     0   
20965        0            0           0                     0   
20966        0            1           1                     0   
20967        0            1           1                     0   

       Quantitative Finance  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  
...                     ...  
20963                     0  
20964                     0  
20965                     0  
20966                     0  
20967                     0  

[20968 rows x 8 columns]

In [ ]:
data.shape

(20968, 8)

In [ ]:
data['TITLE'].unique()

array(['Reconstructing Subject-Specific Effect Maps',
       'Rotation Invariance Neural Network',
       'Spherical polyharmonics and Poisson kernels for polyharmonic functions',
       ..., 'Analysing Soccer Games with Clustering and Conceptors',
       'On the Efficient Simulation of the Left-Tail of the Sum of Correlated Log-normal Variates',
       'Why optional stopping is a problem for Bayesians'], dtype=object)

In [ ]:
data.isnull().sum()

TITLE                   0
ABSTRACT                0
Computer Science        0
Physics                 0
Mathematics             0
Statistics              0
Quantitative Biology    0
Quantitative Finance    0
dtype: int64

In [ ]:
data["Article"] = data[["TITLE", "ABSTRACT"]].apply("-".join, axis=1)
data

TITLE  \
0            Reconstructing Subject-Specific Effect Maps   
1                     Rotation Invariance Neural Network   
2      Spherical polyharmonics and Poisson kernels fo...   
3      A finite element approximation for the stochas...   
4      Comparative study of Discrete Wavelet Transfor...   
...                                                  ...   
20963  Contemporary machine learning: a guide for pra...   
20964  Uniform diamond coatings on WC-Co hard alloy c...   
20965  Analysing Soccer Games with Clustering and Con...   
20966  On the Efficient Simulation of the Left-Tail o...   
20967   Why optional stopping is a problem for Bayesians   

                                                ABSTRACT  Computer Science  \
0        Predictive models allow subject-specific inf...                 1   
1        Rotation invariance and translation invarian...                 1   
2        We introduce and develop the notion of spher...                 0   
3        The stochastic Landau--Lifshitz--Gilbert (LL...                 0   
4        Fourier-transform infra-red (FTIR) spectra o...                 1   
...                                                  ...               ...   
20963    Machine learning is finding increasingly bro...                 1   
20964    Polycrystalline diamond coatings have been g...                 0   
20965    We present a new approach for identifying si...                 1   
20966    The sum of Log-normal variates is encountere...                 0   
20967    Recently, optional stopping has been a subje...                 0   

       Physics  Mathematics  Statistics  Quantitative Biology  \
0            0            0           0                     0   
1            0            0           0                     0   
2            0            1           0                     0   
3            0            1           0                     0   
4            0            0           1                     0   
...        ...          ...         ...                   ...   
20963        1            0           0                     0   
20964        1            0           0                     0   
20965        0            0           0                     0   
20966        0            1           1                     0   
20967        0            1           1                     0   

       Quantitative Finance                                            Article  
0                         0  Reconstructing Subject-Specific Effect Maps-  ...  
1                         0  Rotation Invariance Neural Network-  Rotation ...  
2                         0  Spherical polyharmonics and Poisson kernels fo...  
3                         0  A finite element approximation for the stochas...  
4                         0  Comparative study of Discrete Wavelet Transfor...  
...                     ...                                                ...  
20963                     0  Contemporary machine learning: a guide for pra...  
20964                     0  Uniform diamond coatings on WC-Co hard alloy c...  
20965                     0  Analysing Soccer Games with Clustering and Con...  
20966                     0  On the Efficient Simulation of the Left-Tail o...  
20967                     0  Why optional stopping is a problem for Bayesia...  

[20968 rows x 9 columns]

In [ ]:
df = data[{'Computer Science','Physics','Mathematics','Statistics','Quantitative Biology','Quantitative Finance',	'Article'}]
df

Statistics  Computer Science  Mathematics  \
0               0                 1            0   
1               0                 1            0   
2               0                 0            1   
3               0                 0            1   
4               1                 1            0   
...           ...               ...          ...   
20963           0                 1            0   
20964           0                 0            0   
20965           0                 1            0   
20966           1                 0            1   
20967           1                 0            1   

                                                 Article  \
0      Reconstructing Subject-Specific Effect Maps-  ...   
1      Rotation Invariance Neural Network-  Rotation ...   
2      Spherical polyharmonics and Poisson kernels fo...   
3      A finite element approximation for the stochas...   
4      Comparative study of Discrete Wavelet Transfor...   
...                                                  ...   
20963  Contemporary machine learning: a guide for pra...   
20964  Uniform diamond coatings on WC-Co hard alloy c...   
20965  Analysing Soccer Games with Clustering and Con...   
20966  On the Efficient Simulation of the Left-Tail o...   
20967  Why optional stopping is a problem for Bayesia...   

       Quantitative Biology  Quantitative Finance  Physics  
0                         0                     0        0  
1                         0                     0        0  
2                         0                     0        0  
3                         0                     0        0  
4                         0                     0        0  
...                     ...                   ...      ...  
20963                     0                     0        1  
20964                     0                     0        1  
20965                     0                     0        0  
20966                     0                     0        0  
20967                     0                     0        0  

[20968 rows x 7 columns]

In [ ]:
def clean_text1(text):
    text=text.lower()
    text=re.sub('\[.*?\]','',text)
    text=re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text=re.sub('\w*\d\w*','',text)
    return text

cleaned1=lambda x:clean_text1(x)

In [ ]:
from nltk.tokenize.toktok import ToktokTokenizer

#Tokenization of text
tokenizer=ToktokTokenizer()
#Setting English stopwords
stopword_list=nltk.corpus.stopwords.words('english')

In [ ]:
from bs4 import BeautifulSoup

#Removing the html strips
def strip_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()

In [ ]:
import re,string,unicodedata

#Removing the square brackets
def remove_between_square_brackets(text):
    return re.sub('\[[^]]*\]', '', text)

In [ ]:
#Removing the noisy text
def denoise_text(text):
    text = strip_html(text)
    text = remove_between_square_brackets(text)
    return text

In [ ]:
df['Article']=df['Article'].apply(denoise_text)

<ipython-input-17-a43b774b8e83>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Article']=df['Article'].apply(denoise_text)


In [ ]:
#Define function for removing special characters
def remove_special_characters(text, remove_digits=True):
    pattern=r'[^a-zA-z0-9\s]'
    text=re.sub(pattern,'',text)
    return text

In [ ]:
df['Article']=df['Article'].apply(remove_special_characters)

<ipython-input-19-33851fa8c9d4>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Article']=df['Article'].apply(remove_special_characters)


In [ ]:
#Stemming the text
def simple_stemmer(text):
    ps=nltk.porter.PorterStemmer()
    text= ' '.join([ps.stem(word) for word in text.split()])
    return text

In [ ]:
df['Article']=df['Article'].apply(simple_stemmer)

<ipython-input-21-a33caa5b947b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Article']=df['Article'].apply(simple_stemmer)


In [ ]:
from nltk.corpus import stopwords


#set stopwords to english
stop=set(stopwords.words('english'))
print(stop)

#removing the stopwords
def remove_stopwords(text, is_lower_case=False):
    tokens = tokenizer.tokenize(text)
    tokens = [token.strip() for token in tokens]
    if is_lower_case:
        filtered_tokens = [token for token in tokens if token not in stopword_list]
    else:
        filtered_tokens = [token for token in tokens if token.lower() not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)    
    return filtered_text

{'after', 'by', 'once', 'can', 'won', "you'd", 'own', "doesn't", "needn't", 'my', 'the', 'too', 'some', 'hers', 'weren', "mustn't", 'd', 'that', 'been', 'each', 'myself', 'no', 've', 't', 'doesn', 'isn', 'y', 'theirs', 'about', 'further', 'yourself', 'just', 'where', 'against', 'have', 're', 'yourselves', "shouldn't", 'more', 'his', 'will', 'both', 'with', 'how', "it's", 'am', "aren't", 'you', 'o', "shan't", 'them', 'this', 'mightn', 'had', 'an', 'ma', 'having', 'but', 'not', 'wasn', "won't", 'same', 'through', 'being', 'over', 'here', 'himself', "you've", 'does', 'hadn', 'to', 'very', 'ourselves', 'doing', 'as', 'why', 'couldn', 'was', 'needn', 'what', 'into', "couldn't", 'such', "hasn't", 'yours', 'itself', 'themselves', 'ours', 'now', 'are', 'their', 'herself', 'those', "you're", 'hasn', 'up', 'between', "that'll", "weren't", "haven't", 'didn', 'above', 'it', 'our', 'who', 'she', 'few', 'm', 'for', 'shan', 'off', "you'll", 'most', 'all', 'mustn', 'than', 'me', 'so', 'nor', 'under', 

In [ ]:
df['Article']=df['Article'].apply(remove_stopwords)

<ipython-input-23-008e6fae5e52>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Article']=df['Article'].apply(remove_stopwords)


In [ ]:
from nltk.stem import WordNetLemmatizer,SnowballStemmer

def simple_stemmer(text):
    ps = SnowballStemmer(language='english')
    return ' '.join([ps.stem(word) for word in tokenizer.tokenize(text)])

In [ ]:
data['Article'][0]

"Reconstructing Subject-Specific Effect Maps-  Predictive models allow subject-specific inference when analyzing disease\nrelated alterations in neuroimaging data. Given a subject's data, inference can\nbe made at two levels: global, i.e. identifiying condition presence for the\nsubject, and local, i.e. detecting condition effect on each individual\nmeasurement extracted from the subject's data. While global inference is widely\nused, local inference, which can be used to form subject-specific effect maps,\nis rarely used because existing models often yield noisy detections composed of\ndispersed isolated islands. In this article, we propose a reconstruction\nmethod, named RSM, to improve subject-specific detections of predictive\nmodeling approaches and in particular, binary classifiers. RSM specifically\naims to reduce noise due to sampling error associated with using a finite\nsample of examples to train classifiers. The proposed method is a wrapper-type\nalgorithm that can be used 

In [ ]:
#Lemmatizer example

def lemmatize_all(sentence):
    wnl = WordNetLemmatizer()
    for word, tag in pos_tag(word_tokenize(sentence)):
        if tag.startswith("NN"):
            yield wnl.lemmatize(word, pos='n')
        elif tag.startswith('VB'):
            yield wnl.lemmatize(word, pos='v')
        elif tag.startswith('JJ'):
            yield wnl.lemmatize(word, pos='a')
        else:
            yield word
            
def lemmatize_text(text):
    return ' '.join(lemmatize_all(text))


df['Article'][0]

'reconstruct subjectspecif effect map predict model allow subjectspecif infer analyz diseas relat alter neuroimag data given subject data infer made two level global ie identifiy condit presenc subject local ie detect condit effect individu measur extract subject data global infer wide use local infer use form subjectspecif effect map rare use becaus exist model often yield noisi detect compos dispers isol island thi articl propos reconstruct method name rsm improv subjectspecif detect predict model approach particular binari classifi rsm specif aim reduc nois due sampl error associ use finit sampl exampl train classifi propos method wrappertyp algorithm use differ binari classifi diagnost manner ie without inform condit presenc reconstruct pose maximumaposteriori problem prior model whose paramet estim train data classifierspecif fashion experiment evalu perform synthet gener data data alzheim diseas neuroimag initi adni databas result synthet data demonstr use rsm yield higher detect

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import spacy

nlp = spacy.load("en_core_web_sm")

print("With Count Vectorizer")
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df)
print(vectorizer.get_feature_names_out())
print(X.toarray())
print("\n")
print(cosine_similarity(X))

With Count Vectorizer
['article' 'biology' 'computer' 'finance' 'mathematics' 'physics'
 'quantitative' 'science' 'statistics']
[[0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]]


[[1.  0.  0.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.5 0. ]
 [0.  0.  0.  0.  0.5 1.  0. ]
 [0.  0.  0.  0.  0.  0.  1. ]]


In [ ]:
print("\n\nWith Count Vectorizer and removing stop words")
vectorizer = CountVectorizer(stop_words=nlp.Defaults.stop_words)
X = vectorizer.fit_transform(df)
print(vectorizer.get_feature_names_out())
print(X.toarray())
print("\n")
print(cosine_similarity(X))



With Count Vectorizer and removing stop words
['article' 'biology' 'computer' 'finance' 'mathematics' 'physics'
 'quantitative' 'science' 'statistics']
[[0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0]]


[[1.  0.  0.  0.  0.  0.  0. ]
 [0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  0.5 0. ]
 [0.  0.  0.  0.  0.5 1.  0. ]
 [0.  0.  0.  0.  0.  0.  1. ]]


/usr/local/lib/python3.8/dist-packages/sklearn/feature_extraction/text.py:396: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ll', 've'] not in stop_words.
  warnings.warn(


In [ ]:
print("\n\nWith TFIDFVectorizer")
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df)
print(vectorizer.get_feature_names_out())
print(X.toarray())
print("\n")
print(cosine_similarity(X))



With TFIDFVectorizer
['article' 'biology' 'computer' 'finance' 'mathematics' 'physics'
 'quantitative' 'science' 'statistics']
[[0.         0.         0.         0.         0.         0.
  0.         0.         1.        ]
 [0.         0.         0.70710678 0.         0.         0.
  0.         0.70710678 0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.76944876 0.         0.         0.         0.
  0.63870855 0.         0.        ]
 [0.         0.         0.         0.76944876 0.         0.
  0.63870855 0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.         0.        ]]


[[1.         0.         0.         0.         0.         0.
  0.        ]
 [0.         1.         0.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.

In [ ]:
print("\n\nWith TFIDFVectorizer and removing stop words")
vectorizer = TfidfVectorizer(stop_words=nlp.Defaults.stop_words)
X = vectorizer.fit_transform(df)
print(vectorizer.get_feature_names_out())
print(X.toarray())
print("\n")
print(cosine_similarity(X))



With TFIDFVectorizer and removing stop words
['article' 'biology' 'computer' 'finance' 'mathematics' 'physics'
 'quantitative' 'science' 'statistics']
[[0.         0.         0.         0.         0.         0.
  0.         0.         1.        ]
 [0.         0.         0.70710678 0.         0.         0.
  0.         0.70710678 0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.76944876 0.         0.         0.         0.
  0.63870855 0.         0.        ]
 [0.         0.         0.         0.76944876 0.         0.
  0.63870855 0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.         0.        ]]


[[1.         0.         0.         0.         0.         0.
  0.        ]
 [0.         1.         0.         0.         0.         0.
  0.        ]
 [0.         0.         

In [ ]:
df['Article']

0        reconstruct subjectspecif effect map predict m...
1        rotat invari neural network rotat invari trans...
2        spheric polyharmon poisson kernel polyharmon f...
3        finit element approxim stochast maxwelllandaul...
4        compar studi discret wavelet transform wavelet...
                               ...                        
20963    contemporari machin learn guid practition phys...
20964    uniform diamond coat wcco hard alloy cut inser...
20965    analys soccer game cluster conceptor present n...
20966    effici simul lefttail sum correl lognorm varia...
20967    whi option stop problem bayesian recent option...
Name: Article, Length: 20968, dtype: object

In [ ]:
print(X)

  (0, 8)	1.0
  (1, 7)	0.7071067811865476
  (1, 2)	0.7071067811865476
  (2, 4)	1.0
  (3, 0)	1.0
  (4, 1)	0.7694487573949885
  (4, 6)	0.6387085483562188
  (5, 3)	0.7694487573949885
  (5, 6)	0.6387085483562188
  (6, 5)	1.0


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
X= df.drop("Article", axis=1)
y=df["Article"]
X.head

<bound method NDFrame.head of        Statistics  Computer Science  Mathematics  Quantitative Biology  \
0               0                 1            0                     0   
1               0                 1            0                     0   
2               0                 0            1                     0   
3               0                 0            1                     0   
4               1                 1            0                     0   
...           ...               ...          ...                   ...   
20963           0                 1            0                     0   
20964           0                 0            0                     0   
20965           0                 1            0                     0   
20966           1                 0            1                     0   
20967           1                 0            1                     0   

       Quantitative Finance  Physics  
0                         0        0  
1  

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state = 42)

In [ ]:
# Vectorize the text data
vectorizer = CountVectorizer()
y_train = vectorizer.fit_transform(y_train)
y_test = vectorizer.transform(y_test)

# Convert the sparse matrix to a dense matrix
y_train = y_train.toarray()
y_test = y_test.toarray()

In [ ]:
# Train the linear regression model
model = LogisticRegression()
model.fit(X_train, y_train)

NameError: ignored